spring.application.name=web-empleos-backend
server.port=8081
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://instantjobb2c.b2clogin.com/instantjobb2c.onmicrosoft.com/B2C_1_SUSI/v2.0/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://instantjobb2c.b2clogin.com/instantjobb2c.onmicrosoft.com/B2C_1_SUSI/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audiences=7dd9b923-7aec-407e-b352-7c349ff960a9,1b8c46cb-d440-4839-8a95-e876e2025d18
logging.level.org.springframework.web: DEBUG


spring.datasource.url=jdbc:sqlserver://sql-instantjob-server.database.windows.net:1433;databaseName=db-instantjob-dev
spring.datasource.username=admin-instantjob
spring.datasource.password=Grupo1Duoc
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
